services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    bmehler.contao_hello_world_bundle.message_generator:
        class: Bmehler\ContaoHelloWorldBundle\Library\MessageGenerator
        public: true 